common:
  test_batch_size: 128
  num_workers: 8
  max_iter: 100

  tester: 
    type: "ReIDTester"
    model_path: "reid_lab/HumanBench/PATH/mae_pretrain_vit_large.pth"
    save_dir: "reid_lab/HumanBench/PATH/reid_test_result"
    device: "cuda"
    vis: false

tasks:
  0: 
    name: "reid_test"
    type: "test"
    gres_ratio: 1
    loss_weight : 1.0
    
    dataset: 
      type: "market1501"
      test_only: true
      kwargs:  # 추가해야 하는 부분
        data_path: "/path/to/your/market1501/dataset"  # 실제 데이터셋 경로
        img_size: [256, 128]  # 이미지 크기 [height, width]
        batch_size: 128  # 배치 크기
        num_instances: 4  # 각 ID당 이미지 수 (ReID에서 중요)
        transforms:
          norm_mean: [0.485, 0.456, 0.406]  # 정규화 평균
          norm_std: [0.229, 0.224, 0.225]  # 정규화 표준편차
    
    evaluation:
      type: "rank1_mAP"
      rerank: false
      vis: false  