common:
  test_batch_size: 128
  num_workers: 8
  max_iter: 100

  tester: 
    type: "ReIDTester"
    model_path: "reid_lab/HumanBench/PATH/mae_pretrain_vit_large.pth"
    save_dir: "reid_lab/HumanBench/PATH/reid_test_result"
    device: "cuda"
    vis: false

tasks:
  0: 
    name: "reid_test"
    type: "test"
    gres_ratio: 1
    loss_weight : 1.0
    
    dataset: 
      type: "market1501"  
      test_only: true
    
    evaluation:
      type: "rank1_mAP"
      rerank: false
      vis: false  